spring.application.name=workshop-backend
server.port=${PORT:8080}

# COMMON SETTINGS
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jackson.time-zone=Asia/Kolkata

# DEFAULT = LOCAL (so your project never crashes)
spring.profiles.active=local